# Generated by Django 4.1.3 on 2022-12-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('whatsapp_no', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=15)),
                ('messege', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
