# Generated by Django 4.1.3 on 2022-12-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='whatsapp_no',
            new_name='whatsapp_number',
        ),
    ]
