# Generated by Django 4.1.5 on 2023-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country_code',
            field=models.CharField(default='91', max_length=15, null=True),
        ),
    ]
