# Generated by Django 4.1.5 on 2023-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verification',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
