# Generated by Django 4.1.3 on 2023-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_verification_customer_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='verification_token',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
